# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["<oss@fastly.com>"]
description = "A project for learning about status codes."
language = "javascript"
manifest_version = 3
name = "Golden Girls Codes"
service_id = "SxtNACd4xbV2Z2dWK1koh0"

[scripts]
  build = "npm run build"
  post_init = "npm install"
